### ISSUE TITLE
Constructor with trailing decimal zeros fails

### ISSUE THREAD

**Issue by zouppen** [peterolson/BigRational.js#13] opened 2015-05-07 22:32 UTC
When creating `bigRat` using string which contain trailing zeros after decimal point, it fails:

```javascript
bigRat('2.0')
```

> Error: Invalid integer

On the contrary creating `bigRat` from decimal number without trailing zeros does work (e.g. *2.01*).

**Comment by peterolson** [comment] 2015-06-25 06:19
Sorry for the delay. This seems to be fixed now, I can't reproduce the error. Let me know if the issue persists.

**Closed by peterolson** 2015-06-25 06:19 UTC
